# Generated by Django 3.1 on 2020-08-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_blogs',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='all_blogs',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='all_blogs',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
