# Generated by Django 3.1 on 2020-08-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200831_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All_blogs',
            new_name='Blog',
        ),
    ]
